Program N13L2HIRON;
//HIRON GOLDBACH
CONST UNI:ARRAY[1..9] OF STRING[12]=('UM','DOIS','TRES','QUATRO','CINCO','SEIS','SETE','OITO','NOVE');
      DEZ:ARRAY[1..9] OF STRING[12]=('DEZ','VINTE','TRINTA','QUARENTA','CINQUENTA','SESSENTA','SETENTA','OITENTA','NOVENTA');
      CEN:ARRAY[1..9] OF STRING[12]=('CENTO','DUZENTOS','TREZENTOS','QUATROCENTOS','QUINHENTOS','SEISCENTOS','SETECENTOS','OITOCENTOS','NOVECENTOS');
      EXE:ARRAY[1..9] OF STRING[12]=('ONZE','DOZE','TREZE','QUATORZE','QUINZE','DEZESSEIS','DEZESSETE','DEZOITO','DEZENOVE');
VAR VET:ARRAY[1..3] OF INTEGER;
    A,B,NUM,E:INTEGER;
    TEM_E:BOOLEAN;
Begin
  REPEAT
  	WRITE('DIGITE UM NÚMERO: ');
  	READLN(NUM);
  	IF (NUM>=1000) THEN
  		WRITELN('NÚMERO INVÁLIDO');
  	WRITELN();
  UNTIL(NUM<1000);
  WHILE NUM > 0 DO
  	BEGIN
    	FOR A:=1 TO 3 DO
      	VET[A]:=0;
    	REPEAT 
      	VET[A]:=NUM MOD 10;
				NUM:=NUM DIV 10;
      	A:=A-1;
      UNTIL(NUM=0); 
      TEM_E:=FALSE;
    	IF (VET[1]=1) AND (VET[2]=0) AND (VET[3]=0) THEN
      	WRITELN('CEM')
      ELSE
      	IF (VET[1]<>0) THEN
		  		BEGIN//3
		  			TEM_E:=TRUE;
		  			WRITE(CEN[VET[1]]);
		  			IF (TEM_E) THEN
		  				WRITE(' E '); 
		   		END;
		  IF(VET[2]=1) AND (VET[3]<>0) THEN 
      		WRITE(EXE[VET[3]])
      ELSE    
				IF(VET[2]>1) AND (VET[3]<>0) THEN
			 		BEGIN
			 			TEM_E:=TRUE;
      			WRITE(DEZ[VET[2]]); 
      			IF (TEM_E) THEN
		  				WRITE(' E ');
      		END
      	ELSE
      		IF (VET[2]<>0) AND (VET[3]=0) THEN
      			WRITE(DEZ[VET[2]]); 
      IF (VET[3]<>0) AND (VET[2]<>1) THEN
      	WRITE(UNI[VET[3]]);
			WRITELN();
			WRITELN();
			REPEAT	
				WRITE('DIGITE UM NÚMERO: ');
  			READLN(NUM);
  			IF (NUM>=1000) THEN
  				WRITELN('NÚMERO INVÁLIDO');
  			WRITELN();
			UNTIL(NUM<1000);		
		END;
End.